# Generated by Django 3.0.2 on 2020-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='filmy',
            new_name='actors',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Drama'), (0, 'Nieznany'), (1, 'Horror'), (3, 'Sci-Fi'), (2, 'Komedia')], default=0),
        ),
    ]
