# Generated by Django 3.0.2 on 2020-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200116_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Drama'), (3, 'Sci-Fi'), (0, 'Nieznany'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
    ]
