# Generated by Django 3.0.2 on 2020-01-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200120_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(1, 'Horror'), (3, 'Sci-Fi'), (0, 'Nieznany'), (2, 'Komedia'), (4, 'Drama')], default=0),
        ),
    ]
