# Generated by Django 3.0.2 on 2020-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200121_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Komedia'), (0, 'Nieznany'), (4, 'Drama'), (1, 'Horror'), (3, 'Sci-Fi')], default=0),
        ),
    ]
